---
image: qwe1/dind-ansible-molecule:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ROLE_NAME: ansible-role-docker
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_docker


services:
  - docker:24.0-dind

stages:
  - test

before_script:
  - docker info
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME
  # https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva/1083451#1083451
  # - cat /sys/fs/cgroup/cgroup.controllers

test_d11:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:11-molecule"
  script:
    - molecule --debug test
