---
- name: Remove older versions of Docker(including those in main debian repos)
  apt:
    name:
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Update apt
  apt:
    update_cache: 'yes'
    upgrade: dist

- name: Install needed packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    install_recommends: 'no'

- name: Add docker's apt key
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Setup the docker apt repo
  lineinfile:
    line: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    path: /etc/apt/sources.list.d/docker-ce.list
    create: 'yes'
    owner: root
    group: root
    mode: 0644
    state: present

- name: Install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: 'yes'
    install_recommends: 'no'
  notify: "restart docker"
