---
# configure whether to add or remove users from
# the docker group

- name: Adding docker users if configured
  user:
    name: "{{ item }}"
    groups: "{{ docker_group_name }}"
    append: 'yes'
    state: present
  with_items:
    - "{{ add_docker_users }}"
  when: add_docker_users | length > 0

- name: Removing docker users if configured
  command: gpasswd -d "{{ item }}" "{{ docker_group_name }}"
  register: removal_result
  changed_when: "removal_result.rc != 0"
  with_items:
    - "{{ remove_docker_users }}"
  when: remove_docker_users | length > 0
