---

- name: Update apt cache and add lsb-release to Debian based systems.
  apt:
    update_cache: 'yes'
    name: lsb-release
  when:
    - ansible_os_family == 'Debian'
    - not remove_docker_packages == 'true'

- name: Include tasks specific to Debian.
  include_tasks: "{{ ansible_distribution }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - not ansible_lsb.id == 'Raspbian'
    - not remove_docker_packages == 'true'

- name: Install Docker on Raspbian
  include_tasks: "{{ ansible_lsb.id }}.yml"
  when:
    - ansible_lsb.id == 'Raspbian'
    - not remove_docker_packages == 'true'

- name: Configure docker users
  include_tasks: docker-users.yml
  when:
    - configure_docker_users == 'true'
    - not remove_docker_packages == 'true'

- name: Remove docker packages
  include_tasks: remove-docker.yml
  when:
    - remove_docker_packages == 'true'
