---
# to be fair this task file doesn't
# remove the docker group, or any users from it

- name: Remove docker packages from Debian systems
  ansible.builtin.apt:
   name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-engine
    - docker.io
    - containerd
    - runc
   state: absent
  when:
   - ansible_os_family == 'Debian'

- name: Remove the docker-ce repo from Debian systems
  ansible.builtin.file:
   path: /etc/apt/sources.list.d/docker-ce.list
   state: absent
  when:
   - ansible_os_family == 'Debian'

- name: Remove docker's apt key from Debian systems
  ansible.builtin.apt_key:
   url: 'https://download.docker.com/linux/debian/gpg'
   state: absent
   id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  when:
   - ansible_os_family == 'Debian'
