---
# to be fair this task file doesn't
# remove the docker group, or any users from it

- name: Remove all packages called docker from Red Hat systems
  yum:
   name:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - docker-ce
    - docker-ce-cli
    - containerd.io
   state: absent
  when:
   - ansible_os_family == 'RedHat'

- name: Remove the docker-ce repo from Red Hat systems
  file:
   path: /etc/yum.repos.d/docker-ce.repo
   state: absent
  when:
   - ansible_os_family == 'RedHat'

- name: Remove docker packages from Debian systems
  apt:
   name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-engine
    - docker.io
    - containerd
    - runc
   state: absent
  when:
   - ansible_os_family == 'Debian'

- name: Remove the docker-ce repo from Debian systems
  file:
   path: /etc/apt/sources.list.d/docker-ce.list
   state: absent
  when:
   - ansible_os_family == 'Debian'

- name: Remove docker's apt key from Debian systems
  apt_key:
   url: 'https://download.docker.com/linux/debian/gpg'
   state: absent
   id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  when:
   - ansible_os_family == 'Debian'
